export const links = {
        news:{
            routeWithId:"/news/:id?",
            create:"/create/news/",
            queryList:"/news/"
        },
        specialties:{
            routeWithId:"/specialties/:id?",
            create:"/create/specialty/",
            queryList:"/specialties/"
        },
        specializations:{
            routeWithId:"/specializations/:id?",
            create:"/create/specialization/",
            queryList:"/specializations/"
        },
        departments:{
            routeWithId:"/departments/:id?",
            create:"/create/department/",
            queryList:"/departments/"
        },
        lecturers:{
            routeWithId:"/lecturers/:id?",
            create:"/create/lecturer/",
            queryList:"/lecturers/"
        },
        groups:{
            queryList:"/groups/",
            route:"/groups/",
        },
        academicDegrees:{
            route:"/academic-degrees/",
            queryList:"/academic-degrees/"
        },
        semesters:{
            route:"/semesters/",
            queryList:"/semesters/"
        },
        courses:{
            route:"/courses/",
            queryList:"/courses/"
        },
        users:{
            route:"/users/",
            queryList:"/users/"
        }
}
